'use server';

import { Resend } from 'resend';
import type { ContactFormData } from '@/components/chatbot/contact-form';
import type { Message } from 'ai';

const resend = new Resend(process.env.RESEND_API_KEY);

function formatMessages(messages: Message[]): string {
  return messages
    .map((msg) => {
      const timestamp = msg.createdAt?.toLocaleString();
      const role = msg.role === 'user' ? 'User' : 'Assistant';
      return `
        <div style="margin-bottom: 1rem;">
          <div style="font-weight: bold; color: ${msg.role === 'user' ? '#0A6AE7' : '#212536'}">${role} <span style="font-weight: normal; color: #999;">(${timestamp})</span></div>
          <div style="padding: 0.5rem 1rem; background: #f9f9f9; border-left: 4px solid ${
            msg.role === 'user' ? '#0A6AE7' : '#F5A623'
          }; margin-top: 4px; white-space: pre-line;">${msg.content || '<i>(empty)</i>'}</div>
        </div>
      `;
    })
    .join('');
}

export async function sendEmail({
  data,
  messages,
}: {
  data: ContactFormData;
  messages: Message[];
}) {
  const html = `
    <div style="font-family: 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; padding: 2rem;">
      <h2 style="color: #212536;">New Contact Form Submission</h2>

      <div style="margin-bottom: 2rem;">
        <p><strong>Name:</strong> ${data.name}</p>
        <p><strong>Email:</strong> <a href="mailto:${data.email}">${data.email}</a></p>
      </div>

      <hr style="margin: 2rem 0;" />

      <h3 style="color: #212536;">Chat Transcript</h3>
      ${formatMessages(messages)}

      <hr style="margin: 2rem 0;" />
      <footer style="font-size: 0.8rem; color: #aaa;">Generated by the AI assistant on ${new Date().toLocaleString()}</footer>
    </div>
  `;

  await resend.emails.send({
    from: 'No Reply <noreply@contact.korefocus.com>',
    to: ['thomas@korefocus.com', 'julien.lejay@korefocus.com'],
    subject: `Contact Form: ${data.name}`,
    html,
  });
}
